# Generated by Django 5.1.1 on 2024-09-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
